#!/bin/bash


CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
USER=$(whoami)
for host in `cat $CWD/../../proxy/hosts.txt`
do
	echo $host 
	ssh $host "sqlite3 /virtual/${USER}/URLShortner/urlshortner.db 'SELECT * FROM URLSHORTNER'"
	echo 
done

