#!/bin/bash

CWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
USER=$(whoami)
if [ "$1" == "-n" ]; then
    for host in `cat ../../proxy/hosts.txt`
    do
        ssh $host "mv /virtual/${USER}/URLShortner/new_db.db /virtual/${USER}/URLShortner/urlshortner.db"
        ssh $host "rm -rf /virtual/${USER}/URLShortner/new_db.db"
    done
fi
rm -rf $CWD/../../proxy/hosts.txt
cp $CWD/../../proxy/hosts.txt.new $CWD/../../proxy/hosts.txt

rm -rf $CWD/../../proxy/hosts.txt.new

