#!/bin/bash
echo "Starting on "$(hostname)
LOCALPORT=$2
DBLOCATION=$3
cd ..
if [ "$1" == "-d" ]; then
    java -classpath ".:sqlite-jdbc-3.32.3.2.jar" URLShortner $LOCALPORT $DBLOCATION &> /dev/null &
else
    java -classpath ".:sqlite-jdbc-3.32.3.2.jar" JDBC/DbInit > ./scripts/out/service$(hostname).out 2>./scripts/out/service$(hostname).error < /dev/null
    java -classpath ".:sqlite-jdbc-3.32.3.2.jar" URLShortner > ./scripts/out/service$(hostname).out 2>./scripts/out/service$(hostname).error < /dev/null &
    echo $! > ./scripts/out/service$(hostname).pid;
fi

