#!/bin/bash

# one time tasks
CWD="`pwd`";
echo "waiting for monitoring service to begin."
USER=$(whoami)
# while [ ! -f $CWD'/usage.txt' ]
# do
#   sleep 2
# done
cd ..
javac proxy/*.java
echo "deleting $CWD"
rm -rf $CWD/out/proxy.*

if [ "$1" == "-t" ]; then
    java proxy/Proxy >>/dev/null 2>&1 &
else
    nohup java proxy/Proxy > $CWD/out/proxy.out 2> $CWD/out/proxy.error < /dev/null &
fi

javac URLShortner.java
for host in `cat ./proxy/hosts.txt`
do
	ssh $host "cd \"$CWD\"; ./startNode"
done

# setup recurring tasks
crontab -u ${USER} -l > $CWD/crontab
           /bin/echo "* * * * * /bin/bash -c 'cd /student/${USER}/csc409/repo_a1group10/scripts && ./healthService' > cron.error
* * * * * ( sleep 30 ; /bin/bash -c 'cd /student/${USER}/csc409/repo_a1group10/scripts && ./healthService' > cron.error )" >> $CWD/crontab
crontab $CWD/crontab
rm -rf $CWD/crontab

echo "🚀 started all nodes."
