#!/bin/bash
if [ "$1" == "-d" ]; then
    echo "Stopping on "$(hostname)
    kill -9 $(ps aux | grep URLShortner | grep 8027 | grep java | head -n 1 | awk '{print $2}')
else
    echo "Stopping on "$(hostname)
    kill -9 $(ps aux | grep URLShortner | grep java | head -n 1 | awk '{print $2}')
fi

