#!/bin/bash
CWD="`pwd`";
crontab -r
for host in `cat ../proxy/hosts.txt`
do
	ssh $host "cd \"$CWD\"; ./stopNode"
done
echo "Killing proxy"
kill -9 $(ps aux | grep java | grep proxy/Proxy | head -n 1 | awk '{print $2}')